version: "3.7"

services:
  todo-web:
    image: diamol/ch06-todo-list:v2
    ports:
      - 8089:80
    environment:
      - Database:Provider=Sqlite
    networks:
      - dev_app_net


networks:
  dev_app_net:
    name: "todo_dev_sol"

secrets:
  todo-db-connection:
    file: ./config/empty.json
