version: "3.7"

services:
  accesslog:
    image: diamol/ch04-access-log
    networks:
      - app-net

  iotd:
    image: diamol/ch04-image-of-the-day
    ports:
      - 8088:80
    healthcheck:
      test: ["CMD", "curl", "http://localhost/image"]
      interval: 5s
      timeout: 15s
      retries: 2
      start_period: 10s
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
        failure_action: rollback
        monitor: 60s
        order: start-first
      rollback_config:
        parallelism: 4
        failure_action: continue
        order: start-first
  
    networks:
      - app-net

  image-gallery:
    image: diamol/ch04-image-gallery
    ports:
      - 80:80
    networks:
      - app-net

networks:
  app-net:
    name: image-gallery-prod
