version: "3.7"

services:
  todo-web:
    image: diamol/ch21-todo-list
    ports:
      - 8080:80
    networks:
      - app-net

  todo-db:
    image: diamol/postgres:11.5
    ports:
     - 5444:5432
    networks:
      - app-net

  message-queue:
    image: diamol/nats
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "8222:8222"
    networks:
      - app-net

  save-handler:
    image: diamol/ch21-save-handler
    networks:
      - app-net

networks:
  app-net:
