version: "3.7"

services:
  todo-db:
    image: diamol/postgres:11.5
    restart: unless-stopped
    # https://pgstef.github.io/2018/02/28/custom_pgdata_with_systemd.html
    environment:
      - PGDATA=/var/lib/postgresql/datas
    volumes:
      - type: bind
        source: ./data/postgres
        target: /var/lib/postgresql/datas
    ports:
      - "5438:5432"
    networks:
      - app-net

  todo-web:
    image: diamol/ch06-todo-list
    restart: unless-stopped
    ports:
      - "8050:80"
    environment:
      - Database:Provider=Postgres
    depends_on:
      - todo-db
    networks:
      - app-net
    secrets:
      - source: postgres-connection
        target: /app/config/secrets.json

networks:
  app-net:
    external:
      name: nat

secrets:
  postgres-connection:
    file: ./postgres-connection.json
